
FROM zapiet/php:8.2.5-fpm-alpine3.17-spd


# Configure supervisor
RUN mkdir -p /etc/supervisor.d/
COPY ./docker/api/supervisord.ini /etc/supervisor.d/supervisord.ini

# Configure PHP
RUN mkdir -p /run/php/ \
    && touch /run/php/php81-fpm.pid
# COPY ./docker/php-fpm.conf /etc/php81/php-fpm.conf
COPY ./docker/api/php.ini /usr/local/etc/php/conf.d/php.ini

# Configure nginx
COPY ./docker/api/nginx.conf /etc/nginx/http.d/default.conf
RUN mkdir -p /etc/nginx/cacert
COPY ./docker/nginx-proxy/cacert/cacert.pem /etc/nginx/cacert
RUN mkdir -p /run/nginx/ \
    && touch /run/nginx/nginx.pid

# Configure cron
COPY ./docker/api/crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

ENV WEB_DOCUMENT_ROOT /app/public
WORKDIR /app

# ENV APP_ENV production
# COPY . .


#RUN chown -R www-data:www-data ./bootstrap/cache
#RUN chown -R www-data:www-data ./storage/framework
#RUN chown -R www-data:www-data ./storage/logs

#USER www-data

#COPY ./spd-mothership/composer.json .
#COPY ./spd-mothership/composer.lock .
#ENV COMPOSER_ALLOW_SUPERUSER=1
#RUN composer install --no-interaction --optimize-autoloader

EXPOSE 80
ENTRYPOINT ["supervisord", "-c", "/etc/supervisor.d/supervisord.ini"]
