# For more information: https://laravel.com/docs/sail
version: "3"
name: scheduler
services:
    
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        ports:
            - 443:443
        volumes:
            - ./docker/nginx-proxy/ssl:/etc/nginx/certs
            - ./docker/nginx-proxy/buffer.conf:/etc/nginx/conf.d/buffer.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            default:
                aliases:
                    - api.scheduler.local
                    - phpmyadmin.scheduler.local
    api:
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile-php82
        environment:
            # ssl
            - VIRTUAL_HOST=api.scheduler.local
            - VIRTUAL_PROTO=http
            - VIRTUAL_PORT=80
            - CERT_NAME=localhost
        volumes:
            - .:/app
            - api_vendor:/app/vendor
        expose:
            - 80
#        ports:
#            - "${PUSHER_PORT:-6001}:6001"
        networks:
            - default
        depends_on:
            - mariadb
            
    redis:
        image: redis:alpine
#        ports:
#            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redis_data:/data
        networks:
            - default
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "schedule_api"
            MYSQL_USER: "docker"
            MYSQL_PASSWORD: "docker"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: on-failure
        networks:
            - default
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/1.sql
      

    phpmyadmin:
        image: jackgruber/phpmyadmin:5.0.2
        links:
            - mariadb:db
        environment:
            - PMA_ARBITRARY=0
            - UPLOAD_LIMIT=300M
            # ssl
            - VIRTUAL_HOST=phpmyadmin.scheduler.local
            - VIRTUAL_PROTO=http
            - VIRTUAL_PORT=80
            - CERT_NAME=localhost
        restart: on-failure
        networks:
            - default
        depends_on:
            - mariadb

networks:
    default:
        driver: bridge
        
volumes:
    api_vendor:
    mariadb_data:
    redis_data:
    
