FROM alpine:latest

WORKDIR /app

# Essentials
RUN echo "UTC" > /etc/timezone
RUN apk update
RUN apk add --no-cache curl nginx supervisor

# Installing bash
RUN apk add bash
RUN sed -i 's/bin\/ash/bin\/bash/g' /etc/passwd

# Installing PHP
RUN apk add --no-cache php81 \
    php81-common \
    php81-fpm \
    php81-opcache \
    php81-curl \
    php81-mbstring \
    php81-json \
    php81-xml \
    php81-pdo \
    php81-pdo_mysql \
    # for laravel
    php81-ctype \
    php81-phar \
    php81-dom \
    php81-xmlwriter \
    php81-fileinfo \
    php81-session \
    php81-tokenizer

#    php81-zip \
#    php81-dom \
#    php81-iconv \    
#    php81-openssl \
#    php81-simplexml \
#    php81-cli \
#    php81-pdo_sqlite \
#    php81-pecl-redis

RUN ln -s /usr/bin/php81 /usr/bin/php

# Installing composer
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN rm -rf composer-setup.php

# Configure supervisor
RUN mkdir -p /etc/supervisor.d/
COPY ./docker/supervisord.ini /etc/supervisor.d/supervisord.ini

# Configure PHP
RUN mkdir -p /run/php/
RUN touch /run/php/php81-fpm.pid

COPY ./docker/php-fpm.conf /etc/php81/php-fpm.conf
COPY ./docker/php.ini /etc/php81/php.ini

# Configure nginx
COPY ./docker/nginx.conf /etc/nginx/
COPY ./docker/default.conf /etc/nginx/http.d/

RUN mkdir -p /run/nginx/
RUN touch /run/nginx/nginx.pid

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

# Building process
COPY . .
#RUN composer install --no-dev
#RUN composer update
RUN chown -R nobody:nobody /app/storage

RUN apk add mc

EXPOSE 80
CMD ["supervisord", "-c", "/etc/supervisor.d/supervisord.ini"]
